#!/bin/bash

# --- env_setup.sh ---

# 1. Get the JSON string from the environment variable
CONFIG_JSON_STRING="${OPENBB_ENV_VARS}"

# 2. Check if the variable is set and not empty
if [ -z "$CONFIG_JSON_STRING" ]; then
    echo "Warning: OPENBB_ENV_VARS is not set or is empty. Skipping environment setup."
    exit 0
fi

# 3. Use Python to parse the JSON and generate 'export KEY=VALUE' commands
#    The output of this Python command is captured by the shell.
#    Note: This is set up to print the commands directly to the shell
#    for use in a postCreateCommand or 'source' command.
PYTHON_COMMAND="
import json
import os

try:
    config_dict = json.loads(os.environ['OPENBB_ENV_VARS'])
except json.JSONDecodeError:
    print('Error: OPENBB_ENV_VARS is not valid JSON.', file=os.sys.stderr)
    os.sys.exit(1)
except KeyError:
    # Should be caught by the shell script, but good practice
    os.sys.exit(0)

# Iterate through the dictionary and print 'export' commands
for key, value in config_dict.items():
    # Ensure keys are strings (standard env var practice)
    # Ensure values are quoted for safety in case they contain spaces/special characters
    print(f\"export {key}='{value}'\")
"

# 4. Execute the Python command and evaluate (run) its output in the current shell
#    We use eval to execute the 'export KEY=VALUE' lines generated by Python
eval "$(python3 -c "$PYTHON_COMMAND")"

echo "Success: Environment variables loaded from OPENBB_ENV_VARS."