import os
import json
import sys
import pathlib

# The name of the environment variable that holds the JSON string
CONFIG_ENV_VAR = "OPENBB_ENV_VARS"

# --- New Configuration for IDE Integration ---
# Path where the shell redirects the output of the first function
TEMP_CODESPACE_ENV_PATH = "/tmp/codespace_env_exports"
# Target file the VS Code IDE is configured to read (via settings.json)
TARGET_IDE_ENV_FILE = ".env"
# The directory where the target file should be created (project root)
TARGET_DIR = pathlib.Path.cwd() 

def populate_env_from_json():
    """
    Reads a JSON string from an environment variable and prints
    key-value pairs to standard output in .env format (KEY=VALUE).
    The shell then redirects this output to the temporary file.
    """
    
    # 1. Get the JSON string from the environment
    json_str = os.environ.get(CONFIG_ENV_VAR)
    
    if not json_str:
        # Use sys.stderr for messages so they don't pollute standard output
        print(f"Info: '{CONFIG_ENV_VAR}' environment variable not found.", file=sys.stderr)
        return
        
    try:
        # 2. Parse the JSON string into a Python dictionary
        config_dict = json.loads(json_str)
        
        # 3. Print the variables in plain KEY=VALUE format to standard output (stdout)
        for key, value in config_dict.items():
            env_key = str(key)
            env_value = str(value)
            
            # Print in the required KEY=VALUE format for .env files
            print(f"{env_key}={env_value}")
            
        print("Successfully generated environment variables to stdout.", file=sys.stderr)
            
    except json.JSONDecodeError as e:
        print(f"Error: Failed to decode JSON from {CONFIG_ENV_VAR}. Error: {e}", file=sys.stderr)
    except Exception as e:
        print(f"An unexpected error occurred: {e}", file=sys.stderr)

# --- New Function ---
def copy_env_to_ide_file():
    """
    Copies the contents of the shell-generated temporary environment file 
    to the final .env file that the VS Code IDE is configured to read.
    """
    source_path = TEMP_CODESPACE_ENV_PATH
    target_path = TARGET_DIR / TARGET_IDE_ENV_FILE
    
    if not os.path.exists(source_path):
        print(f"⚠️ Warning: Source environment file not found at: {source_path}", file=sys.stderr)
        print("   Skipping .env creation for IDE.", file=sys.stderr)
        return

    try:
        # 1. Read the content generated by the shell redirection
        with open(source_path, 'r') as f:
            env_content = f.readlines()

        # 2. Write the content to the final target file (i.e., .env)
        with open(target_path, 'w') as f:
            f.writelines(env_content)

        print(f"✅ Success: Copied variables to {target_path} for IDE integration.", file=sys.stderr)

    except Exception as e:
        print(f"❌ Error during IDE .env creation: {e}", file=sys.stderr)


if __name__ == "__main__":
    # Phase 1: Generate the temporary file via shell redirection
    populate_env_from_json()
    
    # Phase 2: Copy the content to the IDE-readable .env file
    # NOTE: This part MUST be run AFTER the shell has finished redirecting 
    # the output of populate_env_from_json() to /tmp/codespace_env_exports.
    # See the 'Automation' section below for how to sequence this correctly.
    
    # For a manual run of the script:
    # If the script is run in two separate steps, or if the shell command
    # that runs this script waits for the redirection to finish,
    # the copy function can be called.
    pass # We'll handle the call externally for the best result.